<a href="https://colab.research.google.com/github/URahul11/ML-LAB-2025-2026/blob/main/statestical_measures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from statistics import mean,median,mode

In [3]:
data=[2,2,4,4,5,6,7,7,8]

In [4]:
print('Mean:',mean(data))
print('Median:',median(data))
print('mode:',mode(data))

Mean: 5
Median: 5
mode: 2


In [6]:
print("Varience:",np.var(data))
print("Standard Deviation:",np.std(data))

Varience: 4.222222222222222
Standard Deviation: 2.0548046676563256


In [7]:
import math
print(math.ceil(3.9))
print(math.trunc(3.4))
print(math.floor(4.5))

4
3
4


In [8]:
print(math.pow(2,3))
print(math.sqrt(21))
print(math.exp(2))
print(math.log(2,3))

8.0
4.58257569495584
7.38905609893065
0.6309297535714574


In [10]:
print(math.sin(math.pi/2))
print(math.cos(0))
print(math.tan(math.pi/4))

print(math.radians(9))

print(math.degrees(math.pi))

1.0
1.0
0.9999999999999999
0.15707963267948966
180.0


In [13]:
print(math.factorial(5))
print(math.gcd(2,6))
print(math.fabs(-9.9))

120
2
9.9


In [14]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


In [15]:
from scipy import constants

print(constants.pi)

print(constants.yotta)
print(constants.zetta)
print(constants.exa)
print(constants.peta)
print(constants.tera)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.pico)
print(constants.femto)
print(constants.atto)
print(constants.zepto)

3.141592653589793
1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [16]:
print(constants.kibi)
print(constants.mebi)
print(constants.gibi)
print(constants.tebi)
print(constants.pebi)
print(constants.exbi)
print(constants.zebi)
print(constants.yobi)

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


In [18]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
arr=np.array([
    [0,1,2],
    [2,2,2],
    [3,3,3]
])
newarr=csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


In [20]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
arr=np.array([
    [0,1,2],
    [2,2,2],
    [3,3,3]
])
newarr=csr_matrix(arr)
print(dijkstra(newarr,return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [21]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [22]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))
